export const Colors = {
  light: {
    canvas: '#fffaf0',
    primary: '#0a0a0a',
    primaryActive: '#1f1f1f',
    primaryDisabled: '#e5e5e5',
    ink: '#0a0a0a',
    bodyStrong: '#1a1a1a',
    body: '#3a3a3a',
    muted: '#6a6a6a',
    mutedSoft: '#9a9a9a',
    hairline: '#e5e5e5',
    hairlineSoft: '#f0f0f0',
    surfaceSoft: '#faf5e8',
    surfaceCard: '#f5f0e0',
    surfaceStrong: '#ebe6d6',
    surfaceDark: '#0a1a1a',
    onPrimary: '#ffffff',
    onDark: '#ffffff',
    brandPink: '#ff4d8b',
    brandTeal: '#1a3a3a',
    brandLavender: '#b8a4ed',
    brandPeach: '#ffb084',
    brandOchre: '#e8b94a',
    brandMint: '#a4d4c5',
    brandCoral: '#ff6b5a',
    success: '#22c55e',
    warning: '#f59e0b',
    error: '#ef4444',
  },
  dark: {
    canvas: '#0f0f0f',
    primary: '#f5f0e0',
    primaryActive: '#ffffff',
    primaryDisabled: '#2a2a2a',
    ink: '#f5f0e0',
    bodyStrong: '#e0dbd0',
    body: '#b0aa9f',
    muted: '#6a6a6a',
    mutedSoft: '#4a4a4a',
    hairline: '#2a2a2a',
    hairlineSoft: '#1f1f1f',
    surfaceSoft: '#1a1a1a',
    surfaceCard: '#1e1e1e',
    surfaceStrong: '#242424',
    surfaceDark: '#0a0a0a',
    onPrimary: '#0a0a0a',
    onDark: '#ffffff',
    brandPink: '#ff4d8b',
    brandTeal: '#2a6a6a',
    brandLavender: '#b8a4ed',
    brandPeach: '#ffb084',
    brandOchre: '#e8b94a',
    brandMint: '#a4d4c5',
    brandCoral: '#ff6b5a',
    success: '#22c55e',
    warning: '#f59e0b',
    error: '#ef4444',
  },
} as const;

export type ColorScheme = 'light' | 'dark';
export type ThemeColors = typeof Colors.light;
