export const Colors = {
  light: {
    canvas: '#fffaf0',
    primary: '#0a0a0a',
    primaryActive: '#1f1f1f',
    primaryDisabled: '#e5e5e5',
    ink: '#0a0a0a',
    bodyStrong: '#1a1a1a',
    body: '#3a3a3a',
    muted: '#6a6a6a',
    mutedSoft: '#9a9a9a',
    hairline: '#e5e5e5',
    hairlineSoft: '#f0f0f0',
    surfaceSoft: '#faf5e8',
    surfaceCard: '#f5f0e0',
    surfaceStrong: '#ebe6d6',
    surfaceDark: '#0a1a1a',
    onPrimary: '#ffffff',
    onDark: '#ffffff',
    brandPink: '#ff4d8b',
    brandTeal: '#1a3a3a',
    brandLavender: '#b8a4ed',
    brandPeach: '#ffb084',
    brandOchre: '#e8b94a',
    brandMint: '#a4d4c5',
    brandCoral: '#ff6b5a',
    brandBlue: '#4d8eff',
    success: '#22c55e',
    warning: '#f59e0b',
    error: '#ef4444',
  },
  dark: {
    canvas: '#080808',
    primary: '#ffffff',
    primaryActive: '#ffffff',
    primaryDisabled: '#2a2a2a',
    ink: '#e1e2ec',
    bodyStrong: '#e1e2ec',
    body: '#c2c6d6',
    muted: '#8c909f',
    mutedSoft: '#6a6a6a',
    hairline: '#262626',
    hairlineSoft: '#1a1a1a',
    surfaceSoft: '#191b23',
    surfaceCard: '#141414',
    surfaceStrong: '#272a31',
    surfaceDark: '#0b0e15',
    onPrimary: '#0a0a0a',
    onDark: '#ffffff',
    brandPink: '#ff4d8b',
    brandTeal: '#2a6a6a',
    brandLavender: '#d0bcff',
    brandPeach: '#ffb084',
    brandOchre: '#ffb786',
    brandMint: '#a4d4c5',
    brandCoral: '#ff6b5a',
    brandBlue: '#4d8eff',
    primaryContainer: '#4d8eff',
    onPrimaryContainer: '#ffffff',
    success: '#22c55e',
    warning: '#f59e0b',
    error: '#ffb4ab',
  },
} as const;

export type ColorScheme = 'light' | 'dark';
export type ThemeColors = typeof Colors.light;
